language: emacs-lisp
before_install:
  - git submodule --quiet update --init
  - if [ "$EMACS" = 'emacs23' ]; then
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs23-gtk emacs23-el;
    fi
  - if [ "$EMACS" = 'emacs24' ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs24 emacs24-el;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq
        emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot;
    fi
matrix:
  allow_failures:
    - env: EMACS=emacs-snapshot
env:
  - EMACS=emacs23
  - EMACS=emacs24
  - EMACS=emacs-snapshot
before_script:
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
        # get bleeding-edge dependencies to go with snapshot
        make downloads-latest;
    else
        make downloads;
    fi
script:
  $EMACS --version &&
  make test EMACS=$EMACS
notifications:
  email: false
